// generated by xUnit Sun Apr 13 2014 10:45:30 GMT+0530 (IST)
// qunit test for ironman.js
// brackets-xunit: qunit
// brackets-xunit: includes=ironman.js
/*global test, ok, equal, isTypeOf */
test("isTypeOf Number", function () {
    "use strict";
    var _param = 4;
    equal(isTypeOf(_param), "number", "isTypeOf(4) equals number");
});

test( "isTypeOf String", function() {
    "use strict";
    var _param = '4';
    equal(isTypeOf(_param), "string", "isTypeOf('4') equals string");
});

test( "isTypeOf Array", function() {
    var isArray = [1,2,3,4,5];
    equal(isTypeOf(isArray), "Array", "isTypeOf([1,2,3]) equals Array");
});

test( "isTypeOf undefined/Null", function() {
    var _param ;
    equal(isTypeOf(_param), "undefined", "isTypeOf() equals undefined");
});

test( "isTypeOf Date", function() {
    var isDate = new Date(06/04/2014);
    ok( isTypeOf(isDate) == "Date", "Passed!" );
});

